# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Mar 26 09:36:09 2024
# ------------------------------------------------

package:
  name: conda
  version: 24.3.0
source:
  fn: conda-24.3.0.tar.gz
  sha256: 017297e3a46193aeac2b7bcbb5064f394a968122b1c1c113c1b1fc1446270f0f
  url: https://github.com/conda/conda/releases/download/24.3.0/conda-24.3.0.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/conda_1711445853354/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --no-build-isolation -vv && /home/conda/feedstock_root/build_artifacts/conda_1711445853354/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m conda init --install
  string: py310hff52083_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - boltons 23.1.1 pyhd8ed1ab_0
    - brotli-python 1.1.0 py310hc6cd4ac_1
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - certifi 2024.2.2 pyhd8ed1ab_0
    - charset-normalizer 3.3.2 pyhd8ed1ab_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - editables 0.5 pyhd8ed1ab_0
    - hatch-vcs 0.4.0 pyhd8ed1ab_0
    - hatchling 1.22.4 pyhd8ed1ab_0
    - idna 3.6 pyhd8ed1ab_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - menuinst 2.0.2 py310hff52083_0
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - packaging 24.0 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.4.0 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - python 3.10.14 hd12c33a_0_cpython
    - python_abi 3.10 4_cp310
    - readline 8.2 h8228510_1
    - requests 2.31.0 pyhd8ed1ab_0
    - ruamel.yaml 0.18.6 py310h2372a71_0
    - ruamel.yaml.clib 0.2.8 py310h2372a71_0
    - setuptools 69.2.0 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - tqdm 4.66.2 pyhd8ed1ab_0
    - trove-classifiers 2024.3.25 pyhd8ed1ab_0
    - typing-extensions 4.10.0 hd8ed1ab_0
    - typing_extensions 4.10.0 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - urllib3 2.2.1 pyhd8ed1ab_0
    - wheel 0.43.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - archspec >=0.2.3
    - boltons >=23.0.0
    - charset-normalizer
    - conda-libmamba-solver >=23.11.0
    - conda-package-handling >=2.2.0
    - distro >=1.5.0
    - jsonpatch >=1.32
    - menuinst >=2
    - packaging >=23.0
    - platformdirs >=3.10.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0
    - zstandard >=0.19.0
  run_constrained:
    - conda-build >=24.3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
test:
  downstreams:
    - conda-smithy
  files:
    - commands_to_test.sh
    - test_runner.sh
  imports:
    - conda
    - conda_env
  requires:
    - mock
    - pexpect
    - responses
about:
  description: 'Conda is an open source package management system and environment

    management system for installing multiple versions of software packages

    and their dependencies and switching easily between them. It works on

    Linux, OS X and Windows, and was created for Python programs but can

    package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://conda.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240326.1.1
  recipe-maintainers:
    - dbast
    - isuruf
    - jakirkham
    - jezdez
    - kenodegard
    - mbargull
    - ocefpaf
  remote_url: https://github.com/conda-forge/conda-feedstock
  sha: 02bcf8ef77a12bb15de9d9dc44066921c7739249
