# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug 17 22:35:19 2023
# ------------------------------------------------

package:
  name: click
  version: 8.1.7
source:
  sha256: ca9853ad459e787e2192211578cc907e7594e294c7ccc834310722b41b9ca6de
  url: https://pypi.io/packages/source/c/click/click-8.1.7.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/click_1692311806742/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv
  string: unix_pyh707e725_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.42.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.2 hd590300_0
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.11.4 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.0.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.1 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - __unix
    - python >=3.8
test:
  commands:
    - pip check
  imports:
    - click
  requires:
    - pip
about:
  description: 'Click is a Python package for creating beautiful command line interfaces

    in a composable way with as little code as necessary. It''s the "Command

    Line Interface Creation Kit". It''s highly configurable but comes with

    sensible defaults out of the box.


    It aims to make the process of writing command line tools quick and fun

    while also preventing any frustration caused by the inability to

    implement an intended CLI API.


    Click in three points:


    -   Arbitrary nesting of commands

    -   Automatic help page generation

    -   Supports lazy loading of subcommands at runtime

    '
  dev_url: https://github.com/pallets/click/
  doc_url: https://click.palletsprojects.com/
  home: https://palletsprojects.com/p/click/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Composable command line interface toolkit
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - xylar
