# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jun 12 21:43:56 2024
# ------------------------------------------------

package:
  name: pydantic
  version: 2.7.4
source:
  sha256: 0c84efd9548d545f63ac0060c1e4d39bb9b14db8b3c0652338aecc07b5adec52
  url: https://pypi.io/packages/source/p/pydantic/pydantic-2.7.4.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pydantic_1718228705123/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps --ignore-installed -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatch-fancy-pypi-readme 24.1.0 pyhd8ed1ab_0
    - hatchling 1.24.2 pyhd8ed1ab_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - ld_impl_linux-64 2.40 hf3520f5_3
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_8
    - libgomp 13.2.0 h77fa898_8
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - packaging 24.1 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pluggy 1.5.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.5.22 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_0
    - typing_extensions 4.12.2 pyha770c72_0
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zipp 3.19.2 pyhd8ed1ab_0
  run:
    - annotated-types >=0.4.0
    - pydantic-core ==2.18.4
    - python >=3.7
    - typing-extensions >=4.6.1
test:
  commands:
    - pip check
  imports:
    - pydantic
  requires:
    - pip
about:
  description: 'Data validation and settings management using python type hinting.

    See documentation <https://docs.pydantic.dev> for more details.

    '
  dev_url: https://github.com/pydantic/pydantic
  doc_url: https://docs.pydantic.dev
  home: https://github.com/pydantic/pydantic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240612.2.1
  recipe-maintainers:
    - davidbrochart
    - dgasmith
    - pavelzw
    - samuelcolvin
  remote_url: https://github.com/conda-forge/pydantic-feedstock
  sha: 4ae1632b147c6803246ab35fdbc54b59cd39a2be
